export {default as Fanfare} from './Fanfare.mp3'
export {default as Tada} from './Tada.mp3'
export {default as Oops} from './Oops.m4a'
export {default as TryAgain} from './TryAgain.mp3'
export {default as ChickenIntro} from './ChickenIntro.mp3'
export {default as CatIntro} from './CatIntro.mp3'
export {default as PresentIntro} from './PresentIntro.mp3'
export {default as IceCreamIntro} from './IceCreamIntro.mp3'